{{- if and (not .Values.auth.useIAMRole) (not .Values.auth.existingSecret) .Values.auth.credentials.accessKeyId .Values.auth.credentials.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-s3-exporter.fullname" . }}
  labels:
    {{- include "helm-s3-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.auth.credentials.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.auth.credentials.secretAccessKey | b64enc | quote }}
{{- end }}

