{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-s3-exporter.serviceAccountName" . }}
  labels:
    {{- include "helm-s3-exporter.labels" . | nindent 4 }}
  {{- if or .Values.serviceAccount.roleArn .Values.serviceAccount.annotations }}
  annotations:
    {{- if .Values.serviceAccount.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}

